[EXP-1160] PopoverCheckboxGroup
pagarme/former-kit pull request #398
Opened 2022-01-31 14:07 UTC by AnderSouza

## Context
- Novo componente de checkboxes que é aberto através de um popover.

## Checklist
- [x] Adicionar componente.
- [x] Adicionar markdown de exemplo.
- [x] Adicionar testes.
- [x] Adicionar stories.

## Linked Issues
- [ \[EXP-1160\] Componente PopoverCheckBox](https://mundipagg.atlassian.net/jira/software/c/projects/EXP/boards/185?modal=detail&selectedIssue=EXP-1160)

## Screenshots
![PopoverCheckboxGroup](https://user-images.githubusercontent.com/11786878/151807966-3c007f69-cc4c-4f29-904f-754f4dfab64c.png)

2022-01-31 14:07 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 45813d7ffbc0978386b4012272f47363a4e411de
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2022-01-31 14:07 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: 45813d7ffbc0978386b4012272f47363a4e411de
  *   
￼ Good titles doesn't exceed 50 characters. To add more details use the body!  

  * lways use the standard `scope: action description`, sempre em inglês  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

2022-01-31 17:55 UTC, Joaovjs reviewed
Não esquece de alterar a versão também no package.json

2022-01-31 17:55 UTC, Joaovjs commented on stories/PopoverCheckboxGroup/style.css
> +  line-height: 32px;
Acho que aqui da para usar uma variavel do CSS que utilizamos em outros lugares para manter o padrão, seria a `--spacing-small` para isso vai precisar fazer o seguinte import: `@import "former-kit-skin-pagarme/dist/styles/spacing.css";`

ref: https://github.com/pagarme/former-kit-skin-pagarme/blob/master/src/styles/spacing.css

2022-01-31 17:55 UTC, Joaovjs commented on src/PopoverCheckboxGroup/style.css
> +  margin: 0 0 24px 0;
Acho que aqui da para usar uma variavel do CSS que utilizamos em outros lugares para manter o padrão, seria a `--spacing-medium` para isso vai precisar fazer o seguinte import: `@import "former-kit-skin-pagarme/dist/styles/spacing.css";`

ref: https://github.com/pagarme/former-kit-skin-pagarme/blob/master/src/styles/spacing.css

2022-01-31 18:04 UTC, Joaovjs reviewed
Na verdade, agora que me toquei que estamos no former-kit... geralmente os estilos do former-kit ficam no former-kit-skin-pagarme, ela só tem os componentes, sem estilização

2022-01-31 18:46 UTC, LorenaKauane reviewed
Além desses comentários 

- Alterar os styles para o former-kit-skin-pagarme (se precisar de ajuda para rodar e testar só me chamar)
- Alterar a version no  package.json

2022-01-31 18:46 UTC, LorenaKauane commented on src/PopoverCheckboxGroup/index.js
> +PopoverCheckboxGroup.propTypes = {
Aqui seguimos um padrão de comentar o que cada `prop` faz, você pode utilizar como exemplo o componente `Tooltip`

2022-01-31 18:46 UTC, LorenaKauane commented on src/PopoverCheckboxGroup/popoverCheckboxGroup.test.js
> +  it('Should close PopoverCheckboxGroup when button is clicked twice.', async () => {
Sugestão de teste:

_Deve selecionar os itens Visa e Mastercard(aqui vc pode escolher qualquer um) e chamar corretamente o onChange_ 

Para você verificar o onChange e algo +- assim:  `expect(onChange).toHaveBeenCalledTimes(1)`

2022-01-31 18:46 UTC, LorenaKauane commented on stories/PopoverCheckboxGroup/index.js
> +  .add('Default', () => (<PopoverCheckboxGroupExample />))
Uma prop que esta invalida, 

Nesse caso aqui eu só abri o componente no storybook e ja retornou nesse erro 
![image](https://user-images.githubusercontent.com/26286922/151852463-f27a9d79-bcf4-47bb-a915-baacb41b1487.png)

2022-01-31 18:46 UTC, LorenaKauane commented on stories/PopoverCheckboxGroup/index.js
> +storiesOf('PopoverCheckboxGroup', module)
Sugestão: Adicionar mais uma stories com o value já selecionado.

2022-01-31 18:46 UTC, LorenaKauane commented on src/PopoverCheckboxGroup/popoverCheckboxGroup.test.js
> +    let title = queryByText('Bandeiras')
Sugestão de teste:

_Deve verificar se os itens Visa e Mastercard(aqui vc pode escolher qualquer um) e está selecionado_ 

Esse caso de cima e quando o value já vem selecionado.

2022-02-02 13:49 UTC, gabriel949 requested changes
Aqui pra mim eu não to conseguindo selecionar um checkbox e quando eu clico em um o popover fecha

2022-02-02 13:49 UTC, gabriel949 commented on src/PopoverCheckboxGroup/index.js
> +  >{children}
Acho que rola de quebrar essa linha

2022-02-02 18:08 UTC, gabriel949 reviewed
Achei um erro aqui mas acho que tá mais para um erro do popover, quando clica em algum lugar do popover sem ser no checkbox ele fecha e fica meio bugado pra abrir de novo

2022-02-02 19:37 UTC, gabriel949 approved these changes

2022-02-03 12:01 UTC, LorenaKauane submitted a review, later dismissed
Depois so verifica com o @Hrfreire se precisa criar uma branch release

2022-02-03 18:47 UTC, LorenaKauane approved these changes

2022-02-03 18:48 UTC, Hrfreire approved these changes

2022-02-03 18:49 UTC, gabriel949 approved these changes

2022-02-03 19:01 UTC, merged